### ISSUE TITLE
The code of the API sequence generation task is not included in this repo. 

### ISSUE THREAD

**Issue by bozheng-hit** [rajasagashe/JuICe-models#1] opened 2019-11-27 04:20 UTC
It seems that the code of the API sequence generation task is not included in this repo.

For the full code generation task, the baseline performance is worse than the results reported in the original paper.  The results I got are 1.5 points lower in bleu(15.88->14.42), 0.5 points lower in EM(1.42->0.93).

**Comment by rajasagashe** [comment] 2019-12-01 04:41
1. The api sequence should be a key in the dataset, so just pass it to the flag `--code-key`.

2. Have you tried multiple runs?

**Comment by bozheng-hit** [comment] 2019-12-01 04:52
1. What do you mean by passing the key to the flag --code-key? The argument is "code_tokens_clean" now.  But there are almost no comments in the code. 
2. I tried three times, the best result is 15.06 in bleu, 1.31 in EM. It seems hard to reproduce the result in the original paper.

**Comment by rajasagashe** [comment] 2019-12-11 05:03
1. You can change that argument from `code_tokens_clean` to `api_sequence`.
2. Are you training on the full dataset? The command listed in the readme trains on 100k.
Thanks for bringing up these questions!

**Comment by bozheng-hit** [comment] 2019-12-17 06:46
1. I changed ``code_tokens_clean`` to ``api_sequence``. The results I got are listed below:
    bleu        em  corpus_bleu  epoch
0  30.811289  23.10213     2.362383   12.0
    bleu        em  corpus_bleu  epoch
0  29.793722  23.21136      1.80322   11.0
What is ``bleu`` and ``em`` here? Do they correspond to precision and recall? If so, I cannot reproduce the results in the original paper of this task, either.
2. I trained the model on the 100k setting.

**Comment by rajasagashe** [comment] 2019-12-19 19:28
1. You can ignore the bleu, em for the api sequence task, I believe the metrics should print out precision and recall in the table so only use those ones.
2. Let me look into this further.

**Comment by bozheng-hit** [comment] 2019-12-20 06:32
I'm pretty sure that precision and recall are not printed. Here is the link to the log file.
https://paste.ubuntu.com/p/zH7Yz6Nhg4/

**Comment by rajasagashe** [comment] 2019-12-22 02:01
They should be getting printed now, also a metrics.json file will be written out in the model directory with the statistics on the best epoch.

**Comment by rajasagashe** [comment] 2019-12-23 20:11
I ran this code again in the different settings you mentioned and here's what I found.
1. 100k train api sequence generation: I could reproduced those numbers.
2. 100k train code generation: Similar to what you got, however see #3.
2. Full train(1.5million) code generation: I'm getting slightly better bleu/em than reported in the paper. This is the most important setting the reproduce as it represents the current best model on the leaderboard. The 100k setting is more just to understand model performance on a smaller subset of data and to speed up prototyping since it's faster to train on. 

Since the numbers are indeed reproducible I'm closing this issue. Thanks for bringing up these questions!

**Closed as completed by rajasagashe** 2019-12-23 20:11 UTC
